# Generated by Django 3.0.7 on 2020-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paparazzo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pic',
            name='photo',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
