# Generated by Django 3.0.7 on 2020-06-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20200626_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Category'),
        ),
    ]
