# Generated by Django 3.0.7 on 2020-06-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20200626_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pic',
            options={'ordering': ['-pub_date']},
        ),
    ]
