# Generated by Django 3.0.7 on 2020-06-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20200627_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='photo',
            new_name='photo_image',
        ),
    ]
